# Generated by Django 5.2.17 on 2026-09-10 13:23

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('explorer', '0001_schemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_key', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('value_type', models.TextField()),
                ('aggregation_method', models.TextField()),
                ('geography_requirement', models.TextField()),
                ('default_frequency', models.TextField()),
                ('source_type', models.TextField()),
                ('status', models.TextField(default='ACTIVE')),
            ],
            options={
                'db_table': '"semantic"."indicator"',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': '"semantic"."metric"',
            },
        ),
        migrations.CreateModel(
            name='TaxOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_owner_key', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': '"semantic"."tax_owner"',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_key', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('dimension', models.TextField()),
                ('symbol', models.TextField()),
            ],
            options={
                'db_table': '"semantic"."unit"',
            },
        ),
        migrations.CreateModel(
            name='BoundarySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_year', models.IntegerField()),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('source_name', models.TextField()),
                ('source_uri', models.TextField()),
                ('asset_uri', models.TextField()),
                ('checksum', models.CharField(max_length=64)),
                ('status', models.TextField(default='ACTIVE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"geo"."boundary_set"',
                'indexes': [models.Index(fields=['reference_year', 'status'], name='boundary_se_referen_5f2751_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('reference_year',), name='unique_active_boundary_set_per_year')],
            },
        ),
        migrations.CreateModel(
            name='DerivedIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('evaluator_key', models.TextField()),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.TextField(default='ACTIVE')),
                ('checksum', models.CharField(max_length=64)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivations', to='explorer.indicator')),
                ('output_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derived_outputs', to='explorer.unit')),
            ],
            options={
                'db_table': '"semantic"."derived_indicator"',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_key', models.TextField(unique=True)),
                ('region_level', models.TextField()),
                ('region_kind', models.TextField()),
                ('valid_period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('status', models.TextField(default='ACTIVE')),
            ],
            options={
                'db_table': '"geo"."region"',
                'indexes': [models.Index(fields=['region_key'], name='region_region__70fc5e_idx'), models.Index(fields=['region_level', 'status'], name='region_region__890b0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type_key', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('valid_period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_types', to='explorer.indicator')),
            ],
            options={
                'db_table': '"semantic"."tax_type"',
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='canonical_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='explorer.unit'),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.TextField(unique=True)),
                ('period_type', models.TextField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('boundary_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods', to='explorer.boundaryset')),
            ],
            options={
                'db_table': '"semantic"."period"',
                'indexes': [models.Index(fields=['period_key'], name='period_period__ccf026_idx'), models.Index(fields=['period_type', 'period_start'], name='period_period__1441a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='BoundaryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.TextField()),
                ('feature_checksum', models.CharField(max_length=64)),
                ('boundary_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features', to='explorer.boundaryset')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boundary_features', to='explorer.region')),
            ],
            options={
                'db_table': '"geo"."boundary_feature"',
                'indexes': [models.Index(fields=['boundary_set', 'region'], name='boundary_fe_boundar_322cde_idx')],
                'constraints': [models.UniqueConstraint(fields=('boundary_set', 'feature_key'), name='unique_feature_key_per_boundary_set')],
            },
        ),
        migrations.CreateModel(
            name='RegionIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_system', models.TextField()),
                ('code', models.TextField()),
                ('valid_period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('source', models.TextField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='explorer.region')),
            ],
            options={
                'db_table': '"geo"."region_identifier"',
                'indexes': [models.Index(fields=['region', 'code_system', 'code'], name='region_iden_region__ab2e66_idx'), models.Index(fields=['code_system', 'code'], name='region_iden_code_sy_ebef26_idx')],
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('code_system', '='), ('code', '='), ('valid_period', '&&')], name='region_identifier_no_overlap')],
            },
        ),
        migrations.CreateModel(
            name='RegionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_type', models.TextField()),
                ('valid_period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('is_official', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='names', to='explorer.region')),
            ],
            options={
                'db_table': '"geo"."region_name"',
                'indexes': [models.Index(fields=['region', 'name_type'], name='region_name_region__50eefa_idx'), models.Index(fields=['name'], name='region_name_name_a45737_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.TextField()),
                ('valid_period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('reason', models.TextField()),
                ('source_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_relations', to='explorer.region')),
                ('target_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_relations', to='explorer.region')),
            ],
            options={
                'db_table': '"geo"."region_relation"',
                'indexes': [models.Index(fields=['source_region', 'target_region'], name='region_rela_source__bde6e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DerivedIndicatorInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('derived_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='explorer.derivedindicator')),
                ('input_indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_derivations', to='explorer.indicator')),
                ('input_metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derived_inputs', to='explorer.metric')),
                ('required_tax_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_inputs', to='explorer.taxowner')),
            ],
            options={
                'db_table': '"semantic"."derived_indicator_input"',
                'constraints': [models.UniqueConstraint(fields=('derived_indicator', 'role'), name='unique_role_per_derived_indicator')],
            },
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['indicator_key'], name='indicator_indicat_e78a43_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['category', 'status'], name='indicator_categor_21d4a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='derivedindicator',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('indicator',), name='unique_active_derived_indicator_per_indicator'),
        ),
        migrations.AddConstraint(
            model_name='derivedindicator',
            constraint=models.UniqueConstraint(fields=('indicator', 'version'), name='unique_derived_indicator_version'),
        ),
    ]
