# Generated by Django 5.2.17 on 2026-09-10 13:24

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_geo_semantic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_key', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': '"catalog"."dataset_family"',
            },
        ),
        migrations.CreateModel(
            name='NormalizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.TextField(unique=True)),
                ('version', models.PositiveIntegerField()),
                ('rule_type', models.TextField()),
                ('parameters', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=64)),
                ('status', models.TextField(default='ACTIVE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"catalog"."normalization_rule"',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_key', models.TextField(unique=True)),
                ('source_provider', models.TextField()),
                ('source_org_id', models.TextField()),
                ('source_table_id', models.TextField()),
                ('source_table_name', models.TextField()),
                ('geography_level', models.TextField()),
                ('frequency', models.TextField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='explorer.datasetfamily')),
            ],
            options={
                'db_table': '"catalog"."dataset"',
            },
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.TextField(default='DRAFT')),
                ('available_period', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_checksum', models.CharField(max_length=64)),
                ('metadata_snapshot', models.JSONField(default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='explorer.dataset')),
            ],
            options={
                'db_table': '"catalog"."dataset_version"',
            },
        ),
        migrations.CreateModel(
            name='DatasetRegionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_dimension', models.TextField()),
                ('source_region_code', models.TextField()),
                ('source_region_name', models.TextField()),
                ('valid_period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('mapping_method', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_mappings', to='explorer.region')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_mappings', to='explorer.datasetversion')),
            ],
            options={
                'db_table': '"catalog"."dataset_region_mapping"',
            },
        ),
        migrations.CreateModel(
            name='DatasetItemMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_item_id', models.TextField()),
                ('source_item_name', models.TextField()),
                ('source_unit_id', models.TextField()),
                ('valid_period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('comparability_status', models.TextField(default='COMPARABLE')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_mappings', to='explorer.indicator')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_mappings', to='explorer.metric')),
                ('tax_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_mappings', to='explorer.taxowner')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_mappings', to='explorer.datasetversion')),
            ],
            options={
                'db_table': '"catalog"."dataset_item_mapping"',
            },
        ),
        migrations.CreateModel(
            name='DatasetDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_dimension', models.TextField(blank=True, null=True)),
                ('semantic_dimension', models.TextField()),
                ('required', models.BooleanField(default=True)),
                ('selection_strategy', models.TextField()),
                ('default_value', models.TextField(blank=True, null=True)),
                ('ordinal', models.IntegerField()),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='explorer.datasetversion')),
            ],
            options={
                'db_table': '"catalog"."dataset_dimension"',
            },
        ),
        migrations.CreateModel(
            name='IndicatorSourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_level', models.TextField()),
                ('valid_period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('authority_status', models.TextField(default='CANDIDATE')),
                ('priority', models.IntegerField(default=100)),
                ('reason', models.TextField(blank=True, default='')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicator_assignments', to='explorer.datasetversion')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_assignments', to='explorer.indicator')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_assignments', to='explorer.metric')),
                ('tax_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_assignments', to='explorer.taxowner')),
            ],
            options={
                'db_table': '"catalog"."indicator_source_assignment"',
            },
        ),
        migrations.CreateModel(
            name='TaxMappingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_tax_code', models.TextField()),
                ('source_tax_name', models.TextField()),
                ('valid_period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('comparability_status', models.TextField(default='COMPARABLE')),
                ('rule_reason', models.TextField(blank=True, default='')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_mapping_rules', to='explorer.datasetversion')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapping_rules', to='explorer.taxtype')),
            ],
            options={
                'db_table': '"catalog"."tax_mapping_rule"',
            },
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.UniqueConstraint(fields=('source_provider', 'source_org_id', 'source_table_id'), name='unique_dataset_source_identity'),
        ),
        migrations.AddConstraint(
            model_name='datasetversion',
            constraint=models.UniqueConstraint(fields=('dataset', 'version'), name='unique_version_per_dataset'),
        ),
        migrations.AddConstraint(
            model_name='datasetversion',
            constraint=models.UniqueConstraint(fields=('dataset', 'metadata_checksum'), name='unique_checksum_per_dataset'),
        ),
        migrations.AddConstraint(
            model_name='datasetversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('dataset',), name='unique_active_version_per_dataset'),
        ),
        migrations.AddConstraint(
            model_name='datasetregionmapping',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('dataset_version', '='), ('source_dimension', '='), ('source_region_code', '='), ('valid_period', '&&')], name='dataset_region_mapping_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='datasetitemmapping',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('dataset_version', '='), ('source_item_id', '='), ('valid_period', '&&')], name='dataset_item_mapping_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='datasetdimension',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('selection_strategy', 'FIXED'), models.Q(('default_value__isnull', True), _negated=True)), models.Q(('selection_strategy', 'FIXED'), _negated=True), _connector='OR'), name='fixed_dimension_requires_default_value'),
        ),
        migrations.AddConstraint(
            model_name='datasetdimension',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('selection_strategy', 'ALL_MAPPED'), models.Q(('source_dimension__isnull', True), _negated=True)), models.Q(('selection_strategy', 'ALL_MAPPED'), _negated=True), _connector='OR'), name='all_mapped_requires_source_dimension'),
        ),
        migrations.AddConstraint(
            model_name='taxmappingrule',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('dataset_version', '='), ('source_tax_code', '='), ('valid_period', '&&')], name='tax_mapping_rule_no_overlap'),
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION catalog.protect_approved_mapping() RETURNS trigger AS $$
            DECLARE parent_status text;
            BEGIN
              SELECT status INTO parent_status
              FROM catalog.dataset_version
              WHERE id = COALESCE(OLD.dataset_version_id, NEW.dataset_version_id);
              IF parent_status IN ('ACTIVE', 'NEEDS_REVIEW', 'RETIRED') THEN
                RAISE EXCEPTION 'approved dataset mappings are immutable';
              END IF;
              RETURN COALESCE(NEW, OLD);
            END;
            $$ LANGUAGE plpgsql;

            CREATE OR REPLACE TRIGGER protect_dimension_trigger
            BEFORE UPDATE OR DELETE ON catalog.dataset_dimension
            FOR EACH ROW EXECUTE FUNCTION catalog.protect_approved_mapping();

            CREATE OR REPLACE TRIGGER protect_item_mapping_trigger
            BEFORE UPDATE OR DELETE ON catalog.dataset_item_mapping
            FOR EACH ROW EXECUTE FUNCTION catalog.protect_approved_mapping();

            CREATE OR REPLACE TRIGGER protect_region_mapping_trigger
            BEFORE UPDATE OR DELETE ON catalog.dataset_region_mapping
            FOR EACH ROW EXECUTE FUNCTION catalog.protect_approved_mapping();

            CREATE OR REPLACE TRIGGER protect_tax_mapping_trigger
            BEFORE UPDATE OR DELETE ON catalog.tax_mapping_rule
            FOR EACH ROW EXECUTE FUNCTION catalog.protect_approved_mapping();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS protect_tax_mapping_trigger ON catalog.tax_mapping_rule;
            DROP TRIGGER IF EXISTS protect_region_mapping_trigger ON catalog.dataset_region_mapping;
            DROP TRIGGER IF EXISTS protect_item_mapping_trigger ON catalog.dataset_item_mapping;
            DROP TRIGGER IF EXISTS protect_dimension_trigger ON catalog.dataset_dimension;
            DROP FUNCTION IF EXISTS catalog.protect_approved_mapping();
            """,
        ),
    ]
