# Generated by Django 5.2.17 on 2026-09-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.TextField()),
                ('status', models.TextField(default='PENDING')),
                ('idempotency_key', models.TextField(unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.IntegerField(default=0)),
                ('raw_row_count', models.IntegerField(default=0)),
                ('normalized_row_count', models.IntegerField(default=0)),
                ('failed_row_count', models.IntegerField(default=0)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_jobs', to='explorer.datasetversion')),
            ],
            options={
                'db_table': '"ingest"."ingestion_job"',
            },
        ),
        migrations.CreateModel(
            name='IngestionSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_key', models.TextField()),
                ('request_parameters', models.JSONField(default=dict)),
                ('status', models.TextField(default='PENDING')),
                ('attempts', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('response_row_count', models.IntegerField(default=0)),
                ('error_code', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slices', to='explorer.ingestionjob')),
            ],
            options={
                'db_table': '"ingest"."ingestion_slice"',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('raw_value', models.TextField(blank=True, default='')),
                ('status', models.TextField(default='PUBLISHED')),
                ('symbol', models.TextField(blank=True, default='')),
                ('quality_status', models.TextField(default='PASSED')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mart_observations', to='explorer.unit')),
                ('derived_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mart_observations', to='explorer.derivedindicator')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='explorer.indicator')),
                ('ingestion_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mart_observations', to='explorer.ingestionjob')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='explorer.metric')),
                ('normalization_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mart_observations', to='explorer.normalizationrule')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='explorer.period')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='explorer.region')),
                ('source_dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mart_observations', to='explorer.datasetversion')),
                ('tax_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='explorer.taxowner')),
            ],
            options={
                'db_table': '"mart"."observation"',
            },
        ),
        migrations.CreateModel(
            name='ObservationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_role', models.TextField()),
                ('derived_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='explorer.observation')),
                ('input_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_as_inputs', to='explorer.observation')),
            ],
            options={
                'db_table': '"mart"."observation_input"',
            },
        ),
        migrations.CreateModel(
            name='RawObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.TextField()),
                ('tbl_id', models.TextField()),
                ('c1', models.TextField(blank=True, default='')),
                ('c1_nm', models.TextField(blank=True, default='')),
                ('c1_obj_nm', models.TextField(blank=True, default='')),
                ('c2', models.TextField(blank=True, default='')),
                ('c2_nm', models.TextField(blank=True, default='')),
                ('c2_obj_nm', models.TextField(blank=True, default='')),
                ('c3', models.TextField(blank=True, default='')),
                ('c3_nm', models.TextField(blank=True, default='')),
                ('c3_obj_nm', models.TextField(blank=True, default='')),
                ('c4', models.TextField(blank=True, default='')),
                ('c4_nm', models.TextField(blank=True, default='')),
                ('c4_obj_nm', models.TextField(blank=True, default='')),
                ('c5', models.TextField(blank=True, default='')),
                ('c5_nm', models.TextField(blank=True, default='')),
                ('c5_obj_nm', models.TextField(blank=True, default='')),
                ('c6', models.TextField(blank=True, default='')),
                ('c6_nm', models.TextField(blank=True, default='')),
                ('c6_obj_nm', models.TextField(blank=True, default='')),
                ('c7', models.TextField(blank=True, default='')),
                ('c7_nm', models.TextField(blank=True, default='')),
                ('c7_obj_nm', models.TextField(blank=True, default='')),
                ('c8', models.TextField(blank=True, default='')),
                ('c8_nm', models.TextField(blank=True, default='')),
                ('c8_obj_nm', models.TextField(blank=True, default='')),
                ('itm_id', models.TextField()),
                ('itm_nm', models.TextField(blank=True, default='')),
                ('unit_id', models.TextField(blank=True, default='')),
                ('unit_nm', models.TextField(blank=True, default='')),
                ('prd_se', models.TextField()),
                ('prd_de', models.TextField()),
                ('dt', models.TextField()),
                ('symbol', models.TextField(blank=True, default='')),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('source_row_hash', models.CharField(max_length=64)),
                ('quality_status', models.TextField(default='UNVALIDATED')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_observations', to='explorer.datasetversion')),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_observations', to='explorer.ingestionjob')),
                ('ingestion_slice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_observations', to='explorer.ingestionslice')),
            ],
            options={
                'db_table': '"ingest"."raw_observation"',
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='source_raw_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mart_observations', to='explorer.rawobservation'),
        ),
        migrations.AddIndex(
            model_name='ingestionslice',
            index=models.Index(fields=['status', 'next_attempt_at'], name='slice_retry_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingestionslice',
            constraint=models.UniqueConstraint(fields=('ingestion_job', 'slice_key'), name='unique_slice_per_job'),
        ),
        migrations.AddConstraint(
            model_name='observationinput',
            constraint=models.UniqueConstraint(fields=('derived_observation', 'input_role'), name='unique_input_role_per_derived_observation'),
        ),
        migrations.AddConstraint(
            model_name='observationinput',
            constraint=models.CheckConstraint(condition=models.Q(('derived_observation', models.F('input_observation')), _negated=True), name='observation_input_no_self_link'),
        ),
        migrations.AddConstraint(
            model_name='rawobservation',
            constraint=models.UniqueConstraint(fields=('ingestion_job', 'source_row_hash'), name='unique_source_row_per_job'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(condition=models.Q(('status', 'PUBLISHED'), ('superseded_at__isnull', True)), fields=['region', 'indicator', 'metric', 'period'], name='obs_series_read_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(condition=models.Q(('status', 'PUBLISHED'), ('superseded_at__isnull', True)), fields=['indicator', 'metric', 'period', 'region'], name='obs_map_rank_read_idx'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_raw_observation__isnull', False), ('source_dataset_version__isnull', False), ('derived_indicator__isnull', True)), models.Q(('source_raw_observation__isnull', True), ('source_dataset_version__isnull', True), ('derived_indicator__isnull', False)), _connector='OR'), name='observation_exactly_one_lineage'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED'), ('superseded_at__isnull', True)), fields=('region', 'period', 'indicator', 'metric', 'tax_owner', 'source_dataset_version'), name='unique_active_source_observation'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED'), ('superseded_at__isnull', True)), fields=('region', 'period', 'indicator', 'metric', 'tax_owner', 'derived_indicator'), name='unique_active_derived_observation'),
        ),
    ]
